<a href="https://colab.research.google.com/github/mkesavaraj97/Python-DA-Assignment--1/blob/main/Python_DA_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
temperatures_w1 = np.array([...])

In [4]:
print("Shape:", temperatures_w1.shape)

Shape: (1,)


In [5]:
print("Shape:", temperatures_w1.shape)

Shape: (1,)


In [6]:
print("Number of Elements:", temperatures_w1.size)

Number of Elements: 1


In [13]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (1,)
Data Type: object
Number of Elements: 1


In [15]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(temperatures_f)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [17]:
maximum_temp = np.max(temperatures_w1)

print("Maximum Temperature:", maximum_temp)

Maximum Temperature: 26.1


In [18]:
minimum_temp = np.min(temperatures_w1)

print("Minimum Temperature:", minimum_temp)

Minimum Temperature: 20.8


In [19]:
mean_temp = np.mean(temperatures_w1)

print("Mean Temperature:", mean_temp)

Mean Temperature: 23.542857142857144


In [20]:
mean_temp = np.mean(temperatures_w1)

print("Mean Temperature:", mean_temp)

Mean Temperature: 23.542857142857144


Array Slicing and Indexing:

In [21]:
first_three_days = temperatures_w1[:3]

print("First Three Days:", first_three_days)

First Three Days: [22.5 25.3 20.8]


In [22]:
weekend = temperatures_w1[-2:]

print("Weekend Temperatures:", weekend)

Weekend Temperatures: [24.8 21.9]


In [23]:
middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:", middle_three_days)

Middle Three Days: [20.8 23.4 26.1]


2D Array


In [24]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [25]:
print("Shape:", temperatures.shape)

Shape: (2, 7)


In [26]:
print("Data Type:", temperatures.dtype)

Data Type: float64


In [27]:
print("Total Number of Elements:", temperatures.size)

Total Number of Elements: 14


In [28]:
week1 = temperatures[0]

print("Week 1:", week1)

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [29]:
week2 = temperatures[1]

print("Week 2:", week2)

Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [30]:
week2 = temperatures[1]

print("Week 2:", week2)

Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


Pandas Series

In [31]:
import pandas as pd

In [32]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [33]:
print(marks[0])

95


/tmp/ipykernel_1116/3296141910.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [34]:
print(marks.iloc[0])

95


In [35]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [36]:
print(marks.iloc[2])

89


In [37]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


In [38]:
marks[marks > 90]

,0
Rank1,95
Rank2,92


Manipulating Series:

In [39]:
marks.loc['Rank1'] = 100

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [40]:
marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [41]:
cgpa = marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


Pandas DataFrame:

In [43]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics' ],
 'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North' ],

    'Amount': [
        200, 150, 300, 450, 200,
        250, 300, 180, 350, 400 ]})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [44]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [45]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [46]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [47]:
print(transactions.shape)

(10, 4)


In [48]:
print(transactions.shape)

(10, 4)


In [49]:
print(transactions.dtypes)


TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [50]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [51]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [52]:
filtered = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [53]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [54]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [55]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [56]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [57]:
transactions['Discount'] = transactions['Amount'] * 0.10

In [58]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     150      15.0
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [59]:
transactions = transactions[
    transactions['TransactionID'] != 109]

In [60]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     150      15.0
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0
